
@if(__DEBUGMODE__)
	Debug.console.visible = true;
@endif

win.bringToFront();

switch(1){
case 1:
	global.game = new SceneManager(win);
	game.changeScene(SCENE_LOGO);
	break;
case 2:
	//引数にセーブファイルがあるか？
	var save = System.getArgument("-save");

	global.game = new SceneManager(win);
	if(save === void)
		game.changeScene(SCENE_LOGO);
	else
		game.changeScene(SCENE_ADV, true, %[file:save]);
	break;
}
delete boot;

function testFuncD(){
	dm("D");
}
function testFuncF(){
	dm("F");
}
